### ISSUE TITLE
Error when building Next JS app

### ISSUE THREAD

**Issue by carlvelasco96** [CreateBaseNZ/school-demo#17]
Hey Louis, I am encountering this error when building the Next JS app.
![Next JS Build](https://user-images.githubusercontent.com/16145959/120128721-ced3fb00-c216-11eb-9088-cebdf972a276.PNG)

**Comment by louis-cf-lin** [comment]
@carlvelasco96 The file is currently empty so I've removed it, can you pull from dev branch and check again

**Comment by carlvelasco96** [comment]
Awesome, it works now @louis-cf-lin
